### PR TITLE
'added-contact-component'

### PR DESCRIPTION
**Pull request by nikhiltripathi1**
I have added a contact widget in the resume module.

Desktop View:
image

Mobile View:
image

### CODE REVIEW

**Comment by nikhiltripathi1** [comment]
@rohanJa 
@ManojSatishkumar 
@WebDevRaj 
@fouzanmohd 
@venkateshpachigulla

**Comment by WebDevRaj** [comment]
Already have an open PR for same component.

**Comment by nikhiltripathi1** [comment]
> Already have an open PR for the same component.

I didn't notice, let that get merged I will update it then. Works?

**Comment by WebDevRaj** [comment]
> > Already have an open PR for the same component.
> 
> I didn't notice, let that get merged I will update it then. Works?

You can add a new variant

**Pull request closed without merging**
